apiVersion: apps/v1
kind: Deployment
metadata:
  name: prevention-point-metabase
  namespace: preventionpoint
  labels:
    owner: prevention-point
    env: demo
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: prevention-point-metabase
        volumeMounts:
        - mountPath: /data/postgres
          name: postgres-tmp-volume
      - name: metabase
        image: metabase/metabase
        ports:
        - containerPort: 3000
        env:
        - name: MB_DB_HOST
          value: localhost
        - name: MB_DB_TYPE
          value: postgres
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_DBNAME
          valueFrom:
            secretKeyRef:
              name: prevention-point-metabase
              key: POSTGRES_DB
        - name: MB_DB_USER
          valueFrom:
            secretKeyRef:
              name: prevention-point-metabase
              key: POSTGRES_USER
        - name: MB_DB_PASS
          valueFrom:
            secretKeyRef:
              name: prevention-point-metabase
              key: POSTGRES_PASSWORD
      volumes:
      - name: postgres-tmp-volume
        emptyDir: {}
